//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualifactChallengeService.Infraestructure.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualifactChallengeService.Infraestructure.Localization.SystemMessages", typeof(SystemMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N/A.
        /// </summary>
        public static string DivisivilityNA {
            get {
                return ResourceManager.GetString("DivisivilityNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input1 must not be zero or negative..
        /// </summary>
        public static string DivisivilityNegativeOrZeroValidation1 {
            get {
                return ResourceManager.GetString("DivisivilityNegativeOrZeroValidation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input2 must not be zero or negative..
        /// </summary>
        public static string DivisivilityNegativeOrZeroValidation2 {
            get {
                return ResourceManager.GetString("DivisivilityNegativeOrZeroValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string DivisivilityNo {
            get {
                return ResourceManager.GetString("DivisivilityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I don&apos;t know.
        /// </summary>
        public static string DivisivilityNotKnown {
            get {
                return ResourceManager.GetString("DivisivilityNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size should be over zero..
        /// </summary>
        public static string DivisivilitySizeValidation {
            get {
                return ResourceManager.GetString("DivisivilitySizeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string DivisivilityYes {
            get {
                return ResourceManager.GetString("DivisivilityYes", resourceCulture);
            }
        }
    }
}
